switch:
  - platform: gpio
    id: cover_open_01_out01
    pin:
      pcf8574: pcf_left
      number: 15
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_01 [cover_open_01_out01, cover_close_01_out02]
    interlock_wait_time: 5ms
    restore_mode: always off

  - platform: gpio
    id: cover_close_01_out02
    pin:
      pcf8574: pcf_left
      number: 14
      mode:
        output: true
      inverted: true
    interlock: *cover_interlock_01
    restore_mode: always off

  - platform: gpio
    id: cover_open_02_out03
    pin:
      pcf8574: pcf_left
      number: 13
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_02 [cover_open_02_out03, cover_close_02_out04]
    interlock_wait_time: 5ms
    restore_mode: always off

  - platform: gpio
    id: cover_close_02_out04
    pin:
      pcf8574: pcf_left
      number: 12
      mode:
        output: true
      inverted: true
    interlock: *cover_interlock_02
    restore_mode: always off

  - platform: gpio
    id: cover_open_03_out05
    pin:
      pcf8574: pcf_left
      number: 11
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_03 [cover_open_03_out05, cover_close_03_out06]
    interlock_wait_time: 5ms
    restore_mode: always off

  - platform: gpio
    id: cover_close_03_out06
    pin:
      pcf8574: pcf_left
      number: 10
      mode:
        output: true
      inverted: true
    interlock: *cover_interlock_03
    restore_mode: always off

  - platform: gpio
    id: cover_open_04_out07
    pin:
      pcf8574: pcf_left
      number: 9
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_04 [cover_open_04_out07, cover_close_04_out08]
    interlock_wait_time: 5ms
    restore_mode: always off

  - platform: gpio
    id: cover_close_04_out08
    pin:
      pcf8574: pcf_left
      number: 8
      mode:
        output: true
      inverted: true
    interlock: *cover_interlock_04
    restore_mode: always off

  - platform: gpio
    id: cover_open_05_out09
    pin:
      pcf8574: pcf_right
      number: 15
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_05 [cover_open_05_out09, cover_close_05_out10]
    interlock_wait_time: 5ms
    restore_mode: always off

  - platform: gpio
    id: cover_close_05_out10
    pin:
      pcf8574: pcf_right
      number: 14
      mode:
        output: true
      inverted: true
    interlock: *cover_interlock_05
    restore_mode: always off

  - platform: gpio
    id: cover_open_06_out11
    pin:
      pcf8574: pcf_right
      number: 13
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_06 [cover_open_06_out11, cover_close_06_out12]
    interlock_wait_time: 5ms
    restore_mode: always off

  - platform: gpio
    id: cover_close_06_out12
    pin:
      pcf8574: pcf_right
      number: 12
      mode:
        output: true
      inverted: true
    interlock: *cover_interlock_06
    restore_mode: always off

  - platform: gpio
    id: cover_open_07_out13
    pin:
      pcf8574: pcf_right
      number: 11
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_07 [cover_open_07_out13, cover_close_07_out14]
    interlock_wait_time: 5ms
    restore_mode: always off

  - platform: gpio
    id: cover_close_07_out14
    pin:
      pcf8574: pcf_right
      number: 10
      mode:
        output: true
      inverted: true
    interlock: *cover_interlock_07
    restore_mode: always off

  - platform: gpio
    id: cover_open_08_out15
    pin:
      pcf8574: pcf_right
      number: 9
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_08 [cover_open_08_out15, cover_close_08_out16]
    interlock_wait_time: 5ms
    restore_mode: always off

  - platform: gpio
    id: cover_close_08_out16
    pin:
      pcf8574: pcf_right
      number: 8
      mode:
        output: true
      inverted: true
    interlock: *cover_interlock_08
    restore_mode: always off

- platform: gpio
    id: cover_open_09_out17
    pin:
      pcf8574: pcf_left
      number: 0
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_01 [cover_open_01_out01, cover_close_01_out02]
    interlock_wait_time: 5ms
    restore_mode: always off

- platform: gpio
    id: cover_close_09_out18
    pin:
      pcf8574: pcf_left
      number: 1
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_01 [cover_open_01_out01, cover_close_01_out02]
    interlock_wait_time: 5ms
    restore_mode: always off

- platform: gpio
    id: cover_open_10_out19
    pin:
      pcf8574: pcf_left
      number: 2
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_01 [cover_open_01_out01, cover_close_01_out02]
    interlock_wait_time: 5ms
    restore_mode: always off

- platform: gpio
    id: cover_close_10_out20
    pin:
      pcf8574: pcf_left
      number: 3
      mode:
        output: true
      inverted: true
    interlock: &cover_interlock_01 [cover_open_01_out01, cover_close_01_out02]
    interlock_wait_time: 5ms
    restore_mode: always off


output:

  - platform: gpio
    id: out_21
    pin:
      pcf8574: pcf_left
      number: 4
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_22
    pin:
      pcf8574: pcf_left
      number: 5
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_23
    pin:
      pcf8574: pcf_left
      number: 6
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_24
    pin:
      pcf8574: pcf_left
      number: 7
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_25
    pin:
      pcf8574: pcf_right
      number: 0
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_26
    pin:
      pcf8574: pcf_right
      number: 1
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_27
    pin:
      pcf8574: pcf_right
      number: 2
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_28
    pin:
      pcf8574: pcf_right
      number: 3
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_29
    pin:
      pcf8574: pcf_right
      number: 4
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_30
    pin:
      pcf8574: pcf_right
      number: 5
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_31
    pin:
      pcf8574: pcf_right
      number: 6
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: out_32
    pin:
      pcf8574: pcf_right
      number: 7
      mode:
        output: true
      inverted: true
